// Generated by the Webflow Cloud builder. Merge logic lives in ./astro.config.webflow.ts.
import { defineConfig } from 'astro/config';
import { readFileSync } from 'node:fs';
import cloudflare from '@astrojs/cloudflare';
import react from '@astrojs/react';
import userConfig from './clouduser.astro.config';
import { withWebflowOverrides } from './astro.config.webflow';

// Detect React 19+ so we know whether to alias react-dom/server -> .edge.
let isReact19 = false;
try {
  const pkg = JSON.parse(readFileSync('./package.json', 'utf8'));
  const reactVersion = pkg.dependencies?.react || pkg.devDependencies?.react || '';
  // Match versions like "19", "^19", "~19", "19.0.0", "^19.0.0", etc.
  isReact19 = /(?:^|[^\d])19(?:\.|$)/.test(reactVersion);
} catch {
  // Could not read package.json, assume not React 19.
}

export default defineConfig(
  withWebflowOverrides(userConfig, {
    mountPath: '/test',
    deployUrl: 'https://110f06dd-c1ea-4839-98af-d829cbe77941.wf-app-prod.cosmic.webflow.services',
    adapter: cloudflare({
      imageService: 'custom',
      // Note: platformProxy removed in Astro 6 — workerd runs natively via @cloudflare/vite-plugin.
    }),
    reactIntegration: react(),
    // Only React 19+ has react-dom/server.edge. React 18 has only .browser, which doesn't run in edge runtimes.
    reactDomServerAlias: import.meta.env.PROD && isReact19
      ? { 'react-dom/server': 'react-dom/server.edge' }
      : undefined,
  })
);
